name: Windows-RDP
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup Windows RDP
        uses: sourabhv/arc-runner-rdp@v1
        with:
          ngrok_token: "3CKVKrAcEEoXkxOA5b5oNpxkLMF_7gjJ8waspaNmuuLHKeXm4"
          password: "MyPassword@123"
