name: Windows-RDP
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Enable Remote Desktop
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          net user runneradmin MyPassword@123
      - name: Start Serveo Tunnel
        shell: cmd
        run: |
          echo ==========================================
          echo Username : runneradmin
          echo Password : MyPassword@123
          echo ==========================================
          ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -R 0:localhost:3389 serveo.net
